<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="4" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="15736" started-at="2019-12-31T05:42:53Z" finished-at="2019-12-31T05:43:08Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="15736" started-at="2019-12-31T05:42:53Z" finished-at="2019-12-31T05:43:08Z">
      <class name="test.wdt">
        <test-method status="FAIL" signature="toclick()[pri:0, instance:test.wdt@740cae06]" name="toclick" duration-ms="14408" started-at="2019-12-31T11:12:53Z" finished-at="2019-12-31T11:13:07Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at test.wdt.toclick(wdt.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- toclick -->
        <test-method status="PASS" signature="verifyDresses()[pri:0, instance:test.wdt@740cae06]" name="verifyDresses" duration-ms="266" started-at="2019-12-31T11:13:07Z" finished-at="2019-12-31T11:13:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyDresses -->
        <test-method status="PASS" signature="verifyTshirt()[pri:0, instance:test.wdt@740cae06]" name="verifyTshirt" duration-ms="427" started-at="2019-12-31T11:13:08Z" finished-at="2019-12-31T11:13:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyTshirt -->
        <test-method status="PASS" signature="verifywomenpage()[pri:0, instance:test.wdt@740cae06]" name="verifywomenpage" duration-ms="50" started-at="2019-12-31T11:13:08Z" finished-at="2019-12-31T11:13:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifywomenpage -->
      </class> <!-- test.wdt -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
